Angular
Bielbiel/kantor pull request #8
Opened 2017-01-26 12:47 UTC by Bielbiel

2017-01-26 13:06 UTC, aniaw requested changes

2017-01-26 13:06 UTC, aniaw commented on app/controllers/ctrlValidate.js
> +            require: 'ngModel-options', link: function (scope, elm, attrs, ctrl)
I didn't see this before. Where did you find this?  `require: 'ngModel-options'` ?

2017-01-26 13:06 UTC, aniaw commented on app/controllers/ctrlValidate.js
> +                    if (ctrl.$isEmpty(modelValue)) {
You can simplify this `if-s` and create only one

2017-01-26 13:06 UTC, aniaw commented on app/controllers/mainCtrl.js
> -            model: null, availableOptions: [{name: 'USD'}, {name: 'EUR'}, {name: 'CHF'}, {name: 'GBP'}, {name: 'CAD'}]
what means `data` - then name of this variable is unintuitive

2017-01-26 13:06 UTC, aniaw commented on app/controllers/mainCtrl.js
> +                ctrl.wallet.EUR = 0;
Can you use here object form?
```
ctrl.wallet = {
EUR: 0,
USD:0,
...
```

2017-01-26 13:06 UTC, aniaw commented on app/controllers/mainCtrl.js
> +                        ctrl.seller = function ()
You have to be consistent in naming. If you create `buy`function you should create `sell` function

2017-01-26 13:06 UTC, aniaw commented on app/views/main.html
> +                <table>
This table look werid. Try to create table in this way:

```
<table border="1" width="100%">
        <thead>
                <tr>
                        <th>Row 1, cell 1</th>
                        <th>Row 1, cell 2</th>
                        <th>Row 2, cell 3</th>
                </tr>
        </thead>
        <tbody>
                <tr>
                        <td>Row 2, cell 1</td>
                        <td>Row 2, cell 2</td>
                        <td>Row 2, cell 3</td>
                </tr>
        </tbody>
</table>
```
with `th` in `thead` and `tr` in `tbody`.

I think you should try to use here ng-repeat.

2017-01-26 13:06 UTC, aniaw commented on app/views/main.html
> +                </div>git
`git`? :P

2017-01-30 08:06 UTC, Bielbiel commented on app/controllers/mainCtrl.js
> +                ctrl.wallet.EUR = 0;
I cant make this becouse function not found

2017-01-30 08:07 UTC, Bielbiel commented on app/controllers/ctrlValidate.js
> +            require: 'ngModel-options', link: function (scope, elm, attrs, ctrl)
Me too but this work :)

2017-01-30 10:42 UTC, merged